/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Data_pb = require('./Data_pb.js');
goog.exportSymbol('proto.com.inferno.protos.RewardEvent', null, global);
goog.exportSymbol('proto.com.inferno.protos.RewardEvent.RewardEventType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.inferno.protos.RewardEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.inferno.protos.RewardEvent.repeatedFields_, null);
};
goog.inherits(proto.com.inferno.protos.RewardEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.inferno.protos.RewardEvent.displayName = 'proto.com.inferno.protos.RewardEvent';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.inferno.protos.RewardEvent.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.inferno.protos.RewardEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.inferno.protos.RewardEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.inferno.protos.RewardEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.inferno.protos.RewardEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventtype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    rewardsList: jspb.Message.toObjectList(msg.getRewardsList(),
    Data_pb.Reward.toObject, includeInstance),
    slot: jspb.Message.getFieldWithDefault(msg, 3, 0),
    userId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.inferno.protos.RewardEvent}
 */
proto.com.inferno.protos.RewardEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.inferno.protos.RewardEvent;
  return proto.com.inferno.protos.RewardEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.inferno.protos.RewardEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.inferno.protos.RewardEvent}
 */
proto.com.inferno.protos.RewardEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.inferno.protos.RewardEvent.RewardEventType} */ (reader.readEnum());
      msg.setEventtype(value);
      break;
    case 2:
      var value = new Data_pb.Reward;
      reader.readMessage(value,Data_pb.Reward.deserializeBinaryFromReader);
      msg.addRewards(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSlot(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.inferno.protos.RewardEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.inferno.protos.RewardEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.inferno.protos.RewardEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.inferno.protos.RewardEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventtype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getRewardsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      Data_pb.Reward.serializeBinaryToWriter
    );
  }
  f = message.getSlot();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.inferno.protos.RewardEvent.RewardEventType = {
  NONE: 0,
  BATTLE_WIN: 1,
  CHEST_OPEN: 2,
  CHEST_BUY: 3
};

/**
 * optional RewardEventType eventType = 1;
 * @return {!proto.com.inferno.protos.RewardEvent.RewardEventType}
 */
proto.com.inferno.protos.RewardEvent.prototype.getEventtype = function() {
  return /** @type {!proto.com.inferno.protos.RewardEvent.RewardEventType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.com.inferno.protos.RewardEvent.RewardEventType} value */
proto.com.inferno.protos.RewardEvent.prototype.setEventtype = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated Reward rewards = 2;
 * @return {!Array<!proto.Reward>}
 */
proto.com.inferno.protos.RewardEvent.prototype.getRewardsList = function() {
  return /** @type{!Array<!proto.Reward>} */ (
    jspb.Message.getRepeatedWrapperField(this, Data_pb.Reward, 2));
};


/** @param {!Array<!proto.Reward>} value */
proto.com.inferno.protos.RewardEvent.prototype.setRewardsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Reward=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Reward}
 */
proto.com.inferno.protos.RewardEvent.prototype.addRewards = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Reward, opt_index);
};


proto.com.inferno.protos.RewardEvent.prototype.clearRewardsList = function() {
  this.setRewardsList([]);
};


/**
 * optional int32 slot = 3;
 * @return {number}
 */
proto.com.inferno.protos.RewardEvent.prototype.getSlot = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.com.inferno.protos.RewardEvent.prototype.setSlot = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string user_id = 4;
 * @return {string}
 */
proto.com.inferno.protos.RewardEvent.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.inferno.protos.RewardEvent.prototype.setUserId = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.com.inferno.protos);
